name: Build SquidpyR package

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pre-commit
        key: precommit-${{ env.pythonLocation }}-${{ hashFiles('.pre-commit-config.yaml') }}

    - name: Install dependencies
      run: |
        sudo apt install pandoc optipng
        python -m pip install --upgrade pip
        pip install tox

    - name: Lint
      run: |
        tox -e lint,check-docs
